export const ActionTypes = {
  FETCH_EMPLOYEE: "FETCH_EMPLOYEE",
  POST_EMPLOYEE: "POST_EMPLOYEE",
  SELECTED_EMPLOYEE: "SELECTED_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
};
