export const ActionTypes = {
  GET_EMPLOYEES: "GET_EMPLOYEES",
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  GET_EMPLOYEE: "GET_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
};
